<?php
namespace Enjin\Sdk\Model;

/**
 * Models a receipt for a blockchain transaction
 * 
 * @copyright (c) 2021, Enjin Pte. Ltd.
 * @author    Mark Jivko, https://markjivko.com
 * @license   Apache License v2.0, https://www.apache.org/licenses/LICENSE-2.0.txt
 */
class TransactionReceipt extends Model {
    
    /**
     * The hash of the block where the transaction is
     * 
     * @var string|null
     */
    protected $_blockHash = null;

    /**
     * The block number where the transaction is
     * 
     * @var int|null
     */
    protected $_blockNumber = null;

    /**
     * The total amount of gas used when the transaction was executed in the block
     * 
     * @var int|null
     */
    protected $_cumulativeGasUsed = null;

    /**
     * The gas used by the specific transaction alone
     * 
     * @var int|null
     */
    protected $_gasUsed = null;

    /**
     * The sender address
     * 
     * @var string|null
     */
    protected $_from = null;

    /**
     * The receiver address, or null when the transaction is for contract creation
     * 
     * @var string|null
     */
    protected $_to = null;

    /**
     * The hash of the transaction
     * 
     * @var string|null
     */
    protected $_transactionHash = null;

    /**
     * The transaction index position in the block
     * 
     * @var int|null
     */
    protected $_transactionIndex = null;

    /**
     * The status of the transaction
     * 
     * @var boolean|null
     */
    protected $_status = null;

    /**
     * List of log objects generated by the transaction
     * 
     * @var TransactionLog[]|null
     */
    protected $_logs = null;
    
    /**
     * The hash of the block where the transaction is
     * 
     * @return string|null
     */
    public function getBlockHash() {
        return $this->_blockHash;
    }

    /**
     * The block number where the transaction is
     * 
     * @return int|null
     */
    public function getBlockNumber() {
        return $this->_blockNumber;
    }

    /**
     * The total amount of gas used when the transaction was executed in the block
     * 
     * @return int|null
     */
    public function getCumulativeGasUsed() {
        return $this->_cumulativeGasUsed;
    }

    /**
     * The gas used by the specific transaction alone
     * 
     * @return int|null
     */
    public function getGasUsed() {
        return $this->_gasUsed;
    }

    /**
     * The sender address
     * 
     * @return string|null
     */
    public function getFrom() {
        return $this->_from;
    }

    /**
     * The receiver address, or null when the transaction is for contract creation
     * 
     * @return string|null
     */
    public function getTo() {
        return $this->_to;
    }

    /**
     * The hash of the transaction
     * 
     * @return string|null
     */
    public function getTransactionHash() {
        return $this->_transactionHash;
    }

    /**
     * The transaction index position in the block
     * 
     * @return int|null
     */
    public function getTransactionIndex() {
        return $this->_transactionIndex;
    }

    /**
     * The status of the transaction
     * 
     * @return boolean|null
     */
    public function getStatus() {
        return $this->_status;
    }

    /**
     * List of log objects generated by the transaction
     * 
     * @return TransactionLog[]|null
     */
    public function getLogs() {
        return $this->_logs;
    }
}

/*EOF*/